### ISSUE TITLE
Allow setting instance configuration from syncano.yml

### ISSUE THREAD

**Issue by forgems** [Syncano/syncano-cli#23]
User should be able to set instance configuration by setting config values in syncano.yml file.
With API version 1.1 this endpoint is exposed at: https://api.syncano.com/v1.1/instances/{instance_name}/snippets/config/

**Comment by bprokop** [comment]
I am unable to find documentation concerning the above endpoint, any help would be much appreciated.

**Comment by opalczynski** [comment]
Help is on the way :)

**Comment by opalczynski** [comment]
Config support was added to syncano CLI in 0.7 version:
https://github.com/Syncano/syncano-cli/#config

It's different approach that suggested - but think that it is enough.
