### ISSUE TITLE
No 'sync' subcommand in cli.

### ISSUE THREAD

**Issue by ndrwtrsk** [Syncano/syncano-cli#25]
Gents, 
in your docs you advise to use `syncano sync pull <instance_name>` to get desired instance, but no such subcommand as `sync` exists in the program. `syncano pull <instance_name>` works just fine however. Is this a planned future and you've just left it here or maybe some omission?

**Comment by opalczynski** [comment]
Hi, we currently works intensively on our CLI - and there's some gap between pypi and the docs, which can you find in this repo. 

Probably will release next version in the next week.
