### ISSUE TITLE
After successful login - show success message 

### ISSUE THREAD

**Issue by MariuszWisniewski** [Syncano/syncano-cli#44]
Right now I think it's not really clear what happened after I typed my password. See screenshot:

<img width="486" alt="screen shot 2016-08-25 at 2 21 35 pm" src="https://cloud.githubusercontent.com/assets/3170386/17980875/4480305c-6acf-11e6-9c51-15496b4e6e1e.png">

**Comment by opalczynski** [comment]
@lifcio Basically everything was good :) If login is unsuccessful - there is an error. But I can add success login message. As I mentioned eariler - Can we stick to jira? :) Or maybe you give this task to community? ;)
