### ISSUE TITLE
Syncano Hosting - missing info what to do after uploading website

### ISSUE THREAD

**Issue by MariuszWisniewski** [Syncano/syncano-cli#45]
See screenshot - after uploading website I don't even know how to open the website - we should have at least a link + some info what to do next, how to edit/update website, how to download it to hard drive, how to stop hosting - right now I don't get that information.

<img width="611" alt="screen shot 2016-08-25 at 2 26 30 pm" src="https://cloud.githubusercontent.com/assets/3170386/17981045/f7c77d46-6acf-11e6-9da0-123ea000d4e1.png">

**Comment by opalczynski** [comment]
@lifcio You already publish files from your hard drive... What you need to download it again? 
Rest of it :) -> will implement. Can we maybe stick to jira? I am a little bit confused with two issues trackers.

**Comment by opalczynski** [comment]
Resolved in CORE-1666
